In [13]:
import anthropic
from datasets import load_dataset
from dotenv import load_dotenv
import os
from datasets import load_from_disk
#python3 -m pip install for any installations

In [5]:
load_dotenv()
client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))


dataset = load_from_disk("diagnosis_arena_data")
type(dataset)

datasets.arrow_dataset.Dataset

In [7]:
df = dataset.to_pandas()

In [9]:
df.head()

,id,Case Information,Physical Examination,Diagnostic Tests,Final Diagnosis,Options,Right Option
0,1,A woman in her early 70s presented with a soli...,"Physical findings revealed an ill-defined, inf...",- Imaging Studies: Brain MRI Title: Paramed...,Cutaneous meningeal heterotopia (CMH),"{'A': 'Cutaneous meningeal heterotopia (CMH)',...",A
1,2,A previously healthy man in his 30s presented ...,Tender black spots on the scrotum were observe...,- Laboratory Tests: Peripheral blood cultures ...,Scrotal ulceration secondary to induction chem...,"{'A': 'Pyoderma gangrenosum', 'B': 'Scrotal ul...",B
2,3,A female patient in her early 50s presented wi...,"Multiple bluish, partially keratotic papules a...",- Sonography: Demonstrated intradermal slow-fl...,Familial cerebral cavernous malformations,{'A': 'Cerebral Cavernous Malformations (CCM)'...,C
3,4,A female patient in her late 20s presented wit...,"Multiple firm, nonscaly, purple erythematous p...",- Histopathological examination: - Thin-wal...,Microvenular hemangioma (MVH),"{'A': 'Epithelioid hemangioma', 'B': 'Morpheaf...",C
4,5,A teenage girl presented with several months o...,"On examination, a left nasal mass was noted. M...",- Imaging Studies: CT scan (without and wit...,Left maxillary giant cell reparative granuloma...,"{'A': 'Ossifying Fibroma', 'B': 'Giant cell tu...",D

In [19]:
import pandas as pd
results = pd.read_csv('diagnosis_results.csv')

In [21]:
results.head()

,predicted,correct
0,Primary cutaneous meningioma (rudimentary/type I),Cutaneous meningeal heterotopia (CMH)
1,Sweet syndrome of the scrotum,Scrotal ulceration secondary to induction chem...
2,Familial cerebral cavernous malformations with...,Familial cerebral cavernous malformations
3,Microvenular hemangioma,Microvenular hemangioma (MVH)
4,Giant cell reparative granuloma of the maxilla...,Left maxillary giant cell reparative granuloma...

In [27]:
results[results['predicted'].isna()]

    predicted                                            correct
447       NaN                         Disseminated protothecosis
453       NaN                                 Sycosis vaccinatum
465       NaN   Painful Left Bundle-Branch Block (LBBB) Syndrome
466       NaN  Epithelial downgrowth after Descemet membrane ...
467       NaN           Progressive nodular histiocytosis (PNHC)
468       NaN  Type B aortic intramural hematoma-induced coro...
469       NaN  Rhabdomyomatous mesenchymal hamartoma (RMH) of...
470       NaN  Iatrogenic cerebrospinal fluid leak with pre-e...
471       NaN     Apical hypertrophic obstructive cardiomyopathy
472       NaN                    COVID-19 (SARS-CoV-2 infection)
473       NaN  COVID-19 with cardiac injury and thrombocytope...
480       NaN                Severe Influenza A (H3N2) infection
503       NaN         Severe Mpox in a patient with advanced HIV
637       NaN                           Laryngeal histoplasmosis
638       NaN  Brucella melitensis soft tissue abscess relate...
704       NaN  Listeria monocytogenes ST87 bacteremia in preg...